# SPDX-FileCopyrightText: 2022 Fraunhofer Institute for Experimental Software Engineering IESE
#
# SPDX-License-Identifier: CC0-1.0

accepted = [
    "Apache-2.0",
    "MIT",
    "CC0-1.0",
    "MPL-2.0",
    "EPL-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
]
